kind: pipeline
name: default

steps:
  - name: build
    image: golang:latest
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - CGO_ENABLED=0 go build 

  - name: docker
    image: plugins/docker
    settings:
      repo: ysicing/godemo
      use_cache: true
      username:
        from_secret: dockeruser
      password:
        from_secret: docker
    tags:
      - latest
    when:
      event: push
      branch: master
